version: '3.8'

services:
  f5-tts-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - F5_MODEL_PATH=F5-TTS
      - VOCODER_MODEL_PATH=charactr/vocos-mel-24khz
      - VOCAB_PATH=Emilia_ZH_EN
      - MAX_SEQUENCE_LENGTH=4096
      - XLA_PYTHON_CLIENT_PREALLOCATE=false
      - JAX_ENABLE_X64=true
    volumes:
      # 挂载模型缓存目录（可选）
      - ./models:/app/models
      # 挂载输出目录（可选）
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # GPU 支持（如果需要）
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # 可选：添加 Nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - f5-tts-api
  #   restart: unless-stopped

volumes:
  models:
  outputs: